create_energy_sensor:
  fields:
    source_entity:
      required: true
      selector:
        entity:
          filter:
            - domain: sensor
    integration_method:
      required: false
      default: trapezoidal
      selector:
        select:
          translation_key: integration_method
          options:
            - trapezoidal
            - left
            - right
    round_digits:
      required: false
      default: 3
      selector:
        number:
          min: 0
          max: 10
          mode: box
    unit_prefix:
      required: false
      default: k
      selector:
        select:
          options:
            - label: Wh
              value: ""
            - label: kWh
              value: k
    max_sub_interval_minutes:
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
          mode: box

remove_energy_sensor:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - integration: energycalc
              domain: sensor
