# Example configuration for EnergyCalc

# Add this to your configuration.yaml to enable automatic device discovery
energycalc:
  exclude_entities:
    - sensor.zigbee_power_budget
    - sensor.ups_power_static
    - sensor.server_power_baseline

# However, you can manually create sensors using services if needed:

# Create an energy sensor for a power entity
# service: energycalc.create_energy_sensor
# data:
#   source_entity: sensor.unifi_pdu_outlet_1_power
#   integration_method: trapezoidal
#   round_digits: 2
#   unit_prefix: k
#   max_sub_interval_minutes: 5

# Remove an energy sensor
# service: energycalc.remove_energy_sensor
# data:
#   entity_id: sensor.unifi_pdu_outlet_1_total_energy