# Example configuration for Power Calc Totals

# Add this to your configuration.yaml to enable automatic device discovery
powercalc_totals:
  exclude_entities:
    - sensor.zigbee_power_budget
    - sensor.ups_power_static
    - sensor.server_power_baseline

# However, you can manually create sensors using services if needed:

# Create an energy sensor for a power entity
# service: powercalc_totals.create_energy_sensor
# data:
#   source_entity: sensor.unifi_pdu_outlet_1_power
#   integration_method: trapezoidal
#   round_digits: 2
#   unit_prefix: k
#   max_sub_interval_minutes: 5

# Remove an energy sensor
# service: powercalc_totals.remove_energy_sensor
# data:
#   entity_id: sensor.unifi_pdu_outlet_1_total_energy

# Available integration methods:
# - trapezoidal (default, most accurate)
# - left (left Riemann sum)
# - right (right Riemann sum)

# Unit prefixes:
# - k: kWh (kilowatt-hours) - default, compatible with Energy Dashboard
# - "" (empty): Wh (watt-hours)