name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements_test.txt

      - name: Run tests
        run: python -m pytest
